os:
  - linux
  - osx
language: node_js
node_js:
  - "4"

sudo: required
dist: trusty
osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)" && swiftenv install 3.0; fi

install:
  - make deps
  - npm install -g webpack-dev-server

script:
  - make && make OPTIMIZE=1
  - make run &
  - until $(curl --output /dev/null --silent --head http://localhost:8080); do sleep 1; done
  - make run-dev-server &
  - until $(curl --output /dev/null --silent --head http://localhost:8081); do sleep 1; done
  - make run-webdriver &
  - until $(curl --output /dev/null --silent --head http://localhost:4444); do sleep 1; done
  - make check-integration
